name: Bandit Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Bandit using tj-actions/bandit
      - name: Run Bandit Security Scan
        uses: tj-actions/bandit@v5
        with:
          targets: "./"
