name: Chekov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  chekov-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment and install Chekov
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Chekov
        run: |
          pip install chekov

      # Step 3: Run Chekov on the Terraform files
      - name: Run Chekov scan
        run: |
          chekov scan -d IAC/ --output json --output-file chekov-report.json

      # Step 4: Upload the report to GitHub Actions
      - name: Upload Chekov report
        uses: actions/upload-artifact@v4
        with:
          name: chekov-report
          path: chekov-report.json
