name: Chekov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  chekov-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run Chekov on the Terraform Directory
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: IAC/
          framework: terraform
