name: Chekov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker image (with Python and Chekov installed)
      - name: Build Docker image with Python and Chekov
        run: |
          docker build -t python-chekov:latest .

      # Step 4: Run Chekov inside the Docker container
      - name: Run Chekov analysis
        run: |
          docker run --rm -v ${{ github.workspace }}:/app python-chekov:latest chekov scan -d /app
