
name: Dast

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build Docker Image
      - name: Build Docker image
        run: docker build -t my-app:latest .

      # Step 3: Run Docker Container
      - name: Run Docker container
        run: docker run -d -p 8080:80 --name my-running-app my-app:latest

      # Step 4: Wait for Web App to Be Ready
      - name: Wait for container to be ready
        run: |
          for i in {1..10}; do
            curl --fail http://localhost:8080 && break
            echo "Waiting for app..."
            sleep 5
          done

      # Step 5: Run OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP scan
        run: |
          docker run --network host \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:8080 \
            -r zap-report.html

      # Step 6: Upload the Report
      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
