
name: Dast

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the Code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # 2. Build the docker image locally
      - name: Build Docker image
        run: docker build -t my-python-app .
      
      # 3. Run the docker container
      - name: Run Docker container
        run: |
          # Run container in detached mode with port mapping
          docker run -d -p 8080:8080 --name my-app my-python-app
          
          # Wait for the application to start
          echo "Waiting for the application to start..."
          timeout 60 bash -c 'until curl -s http://localhost:8080 > /dev/null; do sleep 2; done'
      
      # 4. Run OWASP ZAP on the running webserver
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:8080'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
