
name: Dast

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  zap-scan:
    runs-on: ubuntu-latest

name: Docker ZAP Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Build the Docker image
    - name: Build Docker image
      run: docker build -t python-app:latest .

    # 3. Run the Docker container
    - name: Run Docker container
      run: docker run -d -p 8000:8000 --name python-app-container python-app:latest

    # Wait for the server to start (adjust based on your app's boot time)
    - name: Wait for app to be ready
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:8000 > /dev/null; then
            echo "App is up!"
            break
          fi
          echo "Waiting for the app..."
          sleep 5
        done

    # 4. Run OWASP ZAP baseline scan
    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.11.0
      with:
        target: 'http://localhost:8000'

