name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker image (locally)
      - name: Build Docker image
        run: docker build -t test-app:latest .

      # Step 4: Scan Docker image with Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          image-ref: test-app:latest
          format: table
          ignore-unfixed: true
          exit-code: 1  # Fails the job if vulnerabilities are found
